baseURL = "/"
defaultContentLanguage = ""
defaultContentLanguageInSubdir = false
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "7"
summaryLength = "15"
theme = "meghna-hugo"
title = "Gebäude-Energieberater und Tischlermeister Uli Heinen in Remscheid"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-Us"
languageName = "En"
weight = "1"
[Languages.fr]
contentDir = "content/french"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "kontakt"
name = "Kontakt"
weight = 5
[[menu.main]]
URL = "referenzen"
name = "Referenzen"
weight = 4
[[menu.main]]
URL = "leistungen"
name = "Leistungen"
weight = 3
[[menu.main]]
URL = "energieausweise"
name = "Energieausweis"
weight = 2
[[menu.main]]
URL = "aboutme"
name = "Über mich"
weight = 1
[[menu.main]]
URL = "impressum"
name = "Impressum & Datenschutz"
weight = 6
[params]
author = "Patrick Halbach"
description = "Der Gebäude-Energieberater Uli Heinen in Remscheid Lüttringhausen bietet Ihnen Erfahrung bei Energieberatung beginnend beim Energiepass bis hin zu Modernisierungskonzepten und auch bei Schreinerarbeiten."
keywords = "Gebäude-Energieberater, Energieberater, Uli Heinen, Remscheid, Uli, Heinen, Energieberatung, Energiepass, Gebäudeenergieberatung, Schreinermeister, Schreiner, Tischlermeister, Tischler"
googleAnalitycsID = "Your ID"
logo = "images/logo.png"
postShare = false
social_Icon = []
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/animate-css/animate.css"
[[params.plugins.css]]
URL = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.js]]
URL = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
URL = "plugins/wow/wow.min.js"
[params.preloader]
enable = true
preloader = "images/logo.png"
